#!/bin/bash

export DEBIAN_FRONTEND=non-interactive

###################################

## gcloud sdk

###################################

pip3 install \
    pyasn1 \
    pyasn1-modules \
    google-auth-oauthlib \
    google-cloud

export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)" && \
    echo "deb https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && \
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - && \ 
    apt-get update -qqy && apt-get install google-cloud-sdk -qqy

