#!/bin/bash

################################
## PART: install the packages
##
pkgs=(apt-transport-https
      jq
      vim
      ca-certificates
      python-letsencrypt
      linux-image-extra-virtual
      python3-pip
      lighttpd
)

apt-get -qqy update
apt-get -qqy install ${pkgs[@]}
apt-get -qqy clean
rm -rf /var/lib/apt/lists/*
