#!/bin/bash

################################
## PART: install the packages
##
pkgs=(apache2-utils
      apt-transport-https
      ca-certificates
      certbot
      jq
      kafkacat
      linux-image-extra-virtual
      lighttpd
      python3-pip
      vim
)

apt-get -qqy update
apt-get -y install ${pkgs[@]}
apt-get -qqy clean
rm -rf /var/lib/apt/lists/*
