#!/bin/bash

export DEBIAN_FRONTEND=non-interactive

###################################

## Python data science libraries ##

###################################

#Add ppa in the sources list
add-apt-repository ppa:deadsnakes/ppa

## install python3.8
apt-get update
apt-get upgrade -y
apt-get install -y \
    aria2 \
    python3-pip \
    python3.8 \
    python3-dev \
    python3-virtualenv

apt-get autoremove -y 
apt-get clean

## make some useful symlinks that are expected to exist
#cd /usr/local/bin \
  #&& ln -s idle3 idle \
  #&& ln -s pydoc3 pydoc \
  #&& ln -s python3 python \
  #&& ln -s python3-config python-config


## install jupyter and datascience libraries
pip3 install \
    beautifulsoup4 \
    bokeh \
    jupyter \
    jupyterhub \
    jupyterlab \
    matplotlib \
    networkx \
    nltk \
    notebook \
    numpy \
    pandas \
    pyzmq \
    requests \
    scikit-image \
    scikit-learn \
    scipy \
    seaborn \
    sqlalchemy \
    statsmodels \
    sympy \
    textblob

apt-get -qqy clean
rm -rf /var/lib/apt/lists/*

mkdir -p /var/lib/jupyterhub
